/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Steven
 */
public class EmployeeMenu extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
        this.setTitle("GaMo's Enterprise");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jpnlMinor = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jlblTittle = new javax.swing.JLabel();
        jbtnDriver = new javax.swing.JButton();
        jbtnAdministrator = new javax.swing.JButton();
        jbtnJanitor = new javax.swing.JButton();
        jlbImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlPrincipal.setBackground(new java.awt.Color(255, 204, 204));

        jpnlMinor.setBackground(new java.awt.Color(0, 0, 0));

        jbtnExit.setBackground(new java.awt.Color(153, 0, 0));
        jbtnExit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlMinorLayout = new javax.swing.GroupLayout(jpnlMinor);
        jpnlMinor.setLayout(jpnlMinorLayout);
        jpnlMinorLayout.setHorizontalGroup(
            jpnlMinorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMinorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addContainerGap())
        );
        jpnlMinorLayout.setVerticalGroup(
            jpnlMinorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMinorLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addContainerGap())
        );

        jlblTittle.setBackground(new java.awt.Color(0, 0, 0));
        jlblTittle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTittle.setForeground(new java.awt.Color(0, 0, 0));
        jlblTittle.setText("Choose one");

        jbtnDriver.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDriver.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnDriver.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDriver.setText("Driver");
        jbtnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDriverActionPerformed(evt);
            }
        });

        jbtnAdministrator.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAdministrator.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnAdministrator.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAdministrator.setText("Administrator");
        jbtnAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministratorActionPerformed(evt);
            }
        });

        jbtnJanitor.setBackground(new java.awt.Color(0, 0, 0));
        jbtnJanitor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnJanitor.setForeground(new java.awt.Color(255, 255, 255));
        jbtnJanitor.setText("Janitor");
        jbtnJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJanitorActionPerformed(evt);
            }
        });

        jlbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-groups-64.png"))); // NOI18N

        javax.swing.GroupLayout jpnlPrincipalLayout = new javax.swing.GroupLayout(jpnlPrincipal);
        jpnlPrincipal.setLayout(jpnlPrincipalLayout);
        jpnlPrincipalLayout.setHorizontalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlMinor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnDriver)
                .addGap(29, 29, 29)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jbtnAdministrator)
                        .addGap(34, 34, 34)
                        .addComponent(jbtnJanitor))
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnlPrincipalLayout.setVerticalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDriver)
                    .addComponent(jbtnAdministrator)
                    .addComponent(jbtnJanitor))
                .addGap(27, 27, 27)
                .addComponent(jpnlMinor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDriverActionPerformed

    private void jbtnJanitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJanitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnJanitorActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        this.setVisible(false);
        PrincipalGUI pring= new PrincipalGUI();
        pring.setVisible(true);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministratorActionPerformed
        AdministratorGUI admig= new  AdministratorGUI();
        admig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnAdministratorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAdministrator;
    private javax.swing.JButton jbtnDriver;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnJanitor;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlblTittle;
    private javax.swing.JPanel jpnlMinor;
    private javax.swing.JPanel jpnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
