/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.AdmistratorData;
import Domain.Administrator;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class AdministratorGUI extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form EmployeeGUI
     */
    AdmistratorData adminData= new  AdmistratorData();
    public AdministratorGUI() {
        initComponents();
        this.setTitle("GaMo's Enterprise");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbpMenu = new javax.swing.JTabbedPane();
        jifSignup = new javax.swing.JInternalFrame();
        jpnlSecondary = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jlbImage = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbLastname = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbJobID = new javax.swing.JLabel();
        jlbUniversity = new javax.swing.JLabel();
        jtflName = new javax.swing.JTextField();
        jtflLastname = new javax.swing.JTextField();
        jtflID = new javax.swing.JTextField();
        jtflJobID = new javax.swing.JTextField();
        jlbCategory = new javax.swing.JLabel();
        jbtnSignIn = new javax.swing.JButton();
        jcbxUniversityDegree = new javax.swing.JComboBox<>();
        jcbxCategory = new javax.swing.JComboBox<>();
        jifDelete = new javax.swing.JInternalFrame();
        jpnDelete = new javax.swing.JPanel();
        jpnlSecond = new javax.swing.JPanel();
        jbtnExit2 = new javax.swing.JButton();
        jlbDeleteImage = new javax.swing.JLabel();
        jtflSearch = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jifUpdate = new javax.swing.JInternalFrame();
        jinfList = new javax.swing.JInternalFrame();
        jpnlList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifSignup.setBackground(new java.awt.Color(0, 102, 102));
        jifSignup.setVisible(true);

        jpnlSecondary.setBackground(new java.awt.Color(204, 204, 204));

        jbtnExit.setBackground(new java.awt.Color(255, 0, 51));
        jbtnExit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jlbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-user-group-woman-man-128.png"))); // NOI18N

        javax.swing.GroupLayout jpnlSecondaryLayout = new javax.swing.GroupLayout(jpnlSecondary);
        jpnlSecondary.setLayout(jpnlSecondaryLayout);
        jpnlSecondaryLayout.setHorizontalGroup(
            jpnlSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSecondaryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecondaryLayout.createSequentialGroup()
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jpnlSecondaryLayout.setVerticalGroup(
            jpnlSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecondaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addContainerGap())
        );

        jlbName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbName.setText("Name");

        jlbLastname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbLastname.setText("Lastname");

        jlbID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbID.setText("ID");

        jlbJobID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbJobID.setText("Job ID");

        jlbUniversity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbUniversity.setText("University ");

        jtflID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtflIDActionPerformed(evt);
            }
        });

        jlbCategory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbCategory.setText("Category");

        jbtnSignIn.setBackground(new java.awt.Color(51, 153, 0));
        jbtnSignIn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnSignIn.setText("Sing in");
        jbtnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignInActionPerformed(evt);
            }
        });

        jcbxUniversityDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor's Degrees", "Master's Degrees", "Doctoral Degrees" }));

        jcbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", " " }));

        javax.swing.GroupLayout jifSignupLayout = new javax.swing.GroupLayout(jifSignup.getContentPane());
        jifSignup.getContentPane().setLayout(jifSignupLayout);
        jifSignupLayout.setHorizontalGroup(
            jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifSignupLayout.createSequentialGroup()
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbName)
                    .addComponent(jlbLastname)
                    .addComponent(jlbID)
                    .addComponent(jLabel4)
                    .addComponent(jlbJobID)
                    .addComponent(jlbUniversity)
                    .addComponent(jlbCategory)
                    .addComponent(jbtnSignIn))
                .addGap(77, 77, 77)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtflName, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(jtflLastname)
                        .addComponent(jtflID)
                        .addComponent(jtflJobID))
                    .addComponent(jcbxUniversityDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jpnlSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jifSignupLayout.setVerticalGroup(
            jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlSecondary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jifSignupLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbName)
                    .addComponent(jtflName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtflLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtflID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifSignupLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbJobID))
                    .addComponent(jtflJobID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUniversity)
                    .addComponent(jcbxUniversityDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCategory)
                    .addComponent(jcbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jbtnSignIn)
                .addContainerGap())
        );

        jtbpMenu.addTab("Sign up", jifSignup);

        jifDelete.setVisible(true);

        jpnDelete.setBackground(new java.awt.Color(255, 255, 255));

        jpnlSecond.setBackground(new java.awt.Color(0, 0, 0));

        jbtnExit2.setBackground(new java.awt.Color(153, 0, 0));
        jbtnExit2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit2.setText("Exit");
        jbtnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlSecondLayout = new javax.swing.GroupLayout(jpnlSecond);
        jpnlSecond.setLayout(jpnlSecondLayout);
        jpnlSecondLayout.setHorizontalGroup(
            jpnlSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecondLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit2)
                .addContainerGap())
        );
        jpnlSecondLayout.setVerticalGroup(
            jpnlSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecondLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jbtnExit2)
                .addContainerGap())
        );

        jlbDeleteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-trash-filled-50.png"))); // NOI18N

        jbtnSearch.setBackground(new java.awt.Color(102, 102, 255));
        jbtnSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(153, 0, 0));
        jbtnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Write the name to search");

        javax.swing.GroupLayout jpnDeleteLayout = new javax.swing.GroupLayout(jpnDelete);
        jpnDelete.setLayout(jpnDeleteLayout);
        jpnDeleteLayout.setHorizontalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlSecond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDeleteLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addComponent(jtflSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnSearch)
                        .addGap(12, 12, 12)
                        .addComponent(jbtnDelete))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jlbDeleteImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnDeleteLayout.setVerticalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDeleteLayout.createSequentialGroup()
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtflSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSearch)
                            .addComponent(jbtnDelete)))
                    .addComponent(jlbDeleteImage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jpnlSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jifDeleteLayout = new javax.swing.GroupLayout(jifDelete.getContentPane());
        jifDelete.getContentPane().setLayout(jifDeleteLayout);
        jifDeleteLayout.setHorizontalGroup(
            jifDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jifDeleteLayout.setVerticalGroup(
            jifDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtbpMenu.addTab("Delete", jifDelete);

        jifUpdate.setBackground(new java.awt.Color(51, 255, 204));
        jifUpdate.setVisible(true);

        javax.swing.GroupLayout jifUpdateLayout = new javax.swing.GroupLayout(jifUpdate.getContentPane());
        jifUpdate.getContentPane().setLayout(jifUpdateLayout);
        jifUpdateLayout.setHorizontalGroup(
            jifUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifUpdateLayout.setVerticalGroup(
            jifUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jtbpMenu.addTab("Update", jifUpdate);

        jinfList.setVisible(true);

        javax.swing.GroupLayout jpnlListLayout = new javax.swing.GroupLayout(jpnlList);
        jpnlList.setLayout(jpnlListLayout);
        jpnlListLayout.setHorizontalGroup(
            jpnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        jpnlListLayout.setVerticalGroup(
            jpnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jinfListLayout = new javax.swing.GroupLayout(jinfList.getContentPane());
        jinfList.getContentPane().setLayout(jinfListLayout);
        jinfListLayout.setHorizontalGroup(
            jinfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jinfListLayout.setVerticalGroup(
            jinfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtbpMenu.addTab("List", jinfList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtflIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtflIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtflIDActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       EmployeeMenu emmn= new EmployeeMenu();
       emmn.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExit2ActionPerformed
        EmployeeMenu emmn = new EmployeeMenu();
        emmn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnExit2ActionPerformed

    private void jbtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignInActionPerformed
       Administrator admin= new  Administrator((short)1, jtflName.getText(), jtflLastname.getText(),
               jtflID.getText(),Integer.parseInt(jtflJobID.getText()),true);
     
      AdmistratorData adminData= new  AdmistratorData();
        try {
            adminData.SaveAdministrator(admin);
            JOptionPane.showMessageDialog(null, admin.toString());
        } catch (IOException ex) {
            Logger.getLogger(AdministratorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSignInActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        try {
            
            if(adminData.search(jtflSearch.getText())==true){
                JOptionPane.showMessageDialog(null, "It's founded: "+adminData.getAdmin(jtflName.getText()));
            }else JOptionPane.showMessageDialog(null, "ERROR");
        } catch (IOException ex) {
            Logger.getLogger(AdministratorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
      
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnExit2;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSignIn;
    private javax.swing.JComboBox<String> jcbxCategory;
    private javax.swing.JComboBox<String> jcbxUniversityDegree;
    private javax.swing.JInternalFrame jifDelete;
    private javax.swing.JInternalFrame jifSignup;
    private javax.swing.JInternalFrame jifUpdate;
    private javax.swing.JInternalFrame jinfList;
    private javax.swing.JLabel jlbCategory;
    private javax.swing.JLabel jlbDeleteImage;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlbJobID;
    private javax.swing.JLabel jlbLastname;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbUniversity;
    private javax.swing.JPanel jpnDelete;
    private javax.swing.JPanel jpnlList;
    private javax.swing.JPanel jpnlSecond;
    private javax.swing.JPanel jpnlSecondary;
    private javax.swing.JTabbedPane jtbpMenu;
    private javax.swing.JTextField jtflID;
    private javax.swing.JTextField jtflJobID;
    private javax.swing.JTextField jtflLastname;
    private javax.swing.JTextField jtflName;
    private javax.swing.JTextField jtflSearch;
    // End of variables declaration//GEN-END:variables
}
