/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Steven
 */
public class DriverGUI extends javax.swing.JFrame {

    /**
     * Creates new form JanitorGUI
     */
    public DriverGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jtpnJanitorCRUD = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jpnlAddJanitor = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jlbLastname = new javax.swing.JLabel();
        jlbId = new javax.swing.JLabel();
        jlbJobId = new javax.swing.JLabel();
        jbtnSignIn = new javax.swing.JButton();
        jtxfName = new javax.swing.JTextField();
        jtxfLastname = new javax.swing.JTextField();
        jtxfId = new javax.swing.JTextField();
        jtxfJobId = new javax.swing.JTextField();
        jpnlSecondPanel = new javax.swing.JPanel();
        jbtnExit1 = new javax.swing.JButton();
        jlbIconAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaAddInfo = new javax.swing.JTextArea();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jpnlDelete = new javax.swing.JPanel();
        jpnlSecodDelete = new javax.swing.JPanel();
        jbtnExit2 = new javax.swing.JButton();
        jlbSecondTittle = new javax.swing.JLabel();
        jtxfSearchToDelete = new javax.swing.JTextField();
        jbtnSearchToDelete = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlbDeleteIcon = new javax.swing.JLabel();
        jlbErrorDelete = new javax.swing.JLabel();
        jlbSuccessToDelete = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxfSearchToUpdate = new javax.swing.JTextField();
        jlbIconUpdate = new javax.swing.JLabel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnSearchToUpdate = new javax.swing.JButton();
        jlbNewName = new javax.swing.JLabel();
        jlbLastName = new javax.swing.JLabel();
        jlbNewIdCode = new javax.swing.JLabel();
        jtxfNewName = new javax.swing.JTextField();
        jtxfNewLastname = new javax.swing.JTextField();
        jtxfNewNewJobId = new javax.swing.JTextField();
        jpnlSecond3 = new javax.swing.JPanel();
        jbtnExit3 = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();

        jTextField3.setText("jTextField3");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Write the name to search");

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jpnlAddJanitor.setBackground(new java.awt.Color(255, 255, 255));

        jlbName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbName.setForeground(new java.awt.Color(0, 0, 0));
        jlbName.setText("Name:");

        jlbLastname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbLastname.setForeground(new java.awt.Color(0, 0, 0));
        jlbLastname.setText("Lastname:");

        jlbId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbId.setForeground(new java.awt.Color(0, 0, 0));
        jlbId.setText("ID:");

        jlbJobId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbJobId.setForeground(new java.awt.Color(0, 0, 0));
        jlbJobId.setText("Job ID:");
        jlbJobId.setToolTipText("");

        jbtnSignIn.setBackground(new java.awt.Color(51, 102, 0));
        jbtnSignIn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnSignIn.setText("Sign in");

        javax.swing.GroupLayout jpnlAddJanitorLayout = new javax.swing.GroupLayout(jpnlAddJanitor);
        jpnlAddJanitor.setLayout(jpnlAddJanitorLayout);
        jpnlAddJanitorLayout.setHorizontalGroup(
            jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAddJanitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSignIn)
                    .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbName)
                        .addComponent(jlbLastname)
                        .addComponent(jlbId)
                        .addComponent(jlbJobId)))
                .addGap(47, 47, 47)
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxfName)
                    .addComponent(jtxfLastname)
                    .addComponent(jtxfId)
                    .addComponent(jtxfJobId, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpnlAddJanitorLayout.setVerticalGroup(
            jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAddJanitorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbName)
                    .addComponent(jtxfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLastname)
                    .addComponent(jtxfLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbId)
                    .addComponent(jtxfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpnlAddJanitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbJobId)
                    .addComponent(jtxfJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSignIn)
                .addContainerGap())
        );

        jbtnExit1.setBackground(new java.awt.Color(153, 0, 0));
        jbtnExit1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit1.setText("Exit");

        jlbIconAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-user-group-woman-man-128.png"))); // NOI18N

        jtxaAddInfo.setColumns(20);
        jtxaAddInfo.setRows(5);
        jScrollPane1.setViewportView(jtxaAddInfo);

        javax.swing.GroupLayout jpnlSecondPanelLayout = new javax.swing.GroupLayout(jpnlSecondPanel);
        jpnlSecondPanel.setLayout(jpnlSecondPanelLayout);
        jpnlSecondPanelLayout.setHorizontalGroup(
            jpnlSecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSecondPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlSecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnExit1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlSecondPanelLayout.createSequentialGroup()
                .addComponent(jlbIconAdd)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnlSecondPanelLayout.setVerticalGroup(
            jpnlSecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecondPanelLayout.createSequentialGroup()
                .addComponent(jlbIconAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnExit1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jpnlAddJanitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnlSecondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlAddJanitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlSecondPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpnJanitorCRUD.addTab("Add", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpnlDelete.setBackground(new java.awt.Color(255, 255, 255));

        jbtnExit2.setBackground(new java.awt.Color(153, 0, 0));
        jbtnExit2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit2.setText("Exit");

        javax.swing.GroupLayout jpnlSecodDeleteLayout = new javax.swing.GroupLayout(jpnlSecodDelete);
        jpnlSecodDelete.setLayout(jpnlSecodDeleteLayout);
        jpnlSecodDeleteLayout.setHorizontalGroup(
            jpnlSecodDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecodDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit2)
                .addContainerGap())
        );
        jpnlSecodDeleteLayout.setVerticalGroup(
            jpnlSecodDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecodDeleteLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jbtnExit2)
                .addGap(20, 20, 20))
        );

        jlbSecondTittle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbSecondTittle.setForeground(new java.awt.Color(0, 0, 0));
        jlbSecondTittle.setText("Write the name to search");

        jbtnSearchToDelete.setBackground(new java.awt.Color(51, 51, 255));
        jbtnSearchToDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnSearchToDelete.setText("Search");
        jbtnSearchToDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchToDeleteActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(153, 0, 0));
        jbtnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jlbDeleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-trash-filled-50.png"))); // NOI18N

        jlbErrorDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbErrorDelete.setForeground(new java.awt.Color(0, 0, 0));
        jlbErrorDelete.setText("This person does not exist");

        jlbSuccessToDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbSuccessToDelete.setForeground(new java.awt.Color(0, 0, 0));
        jlbSuccessToDelete.setText("¡Success to delete!");

        javax.swing.GroupLayout jpnlDeleteLayout = new javax.swing.GroupLayout(jpnlDelete);
        jpnlDelete.setLayout(jpnlDeleteLayout);
        jpnlDeleteLayout.setHorizontalGroup(
            jpnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDeleteLayout.createSequentialGroup()
                .addGroup(jpnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDeleteLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jbtnSearchToDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlDeleteLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3))
                            .addGroup(jpnlDeleteLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jlbDeleteIcon))
                            .addGroup(jpnlDeleteLayout.createSequentialGroup()
                                .addComponent(jtxfSearchToDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDelete))
                            .addComponent(jlbErrorDelete)
                            .addComponent(jlbSecondTittle)))
                    .addGroup(jpnlDeleteLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jlbSuccessToDelete)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(jpnlSecodDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnlDeleteLayout.setVerticalGroup(
            jpnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSecondTittle)
                .addGap(18, 18, 18)
                .addGroup(jpnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfSearchToDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearchToDelete)
                    .addComponent(jbtnDelete))
                .addGap(30, 30, 30)
                .addComponent(jlbDeleteIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbErrorDelete)
                .addGap(18, 18, 18)
                .addComponent(jlbSuccessToDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jpnlSecodDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jpnlDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpnlDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpnJanitorCRUD.addTab("Delete", jInternalFrame2);

        jInternalFrame3.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Write the ID   ");

        jlbIconUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-downloading-updates-64.png"))); // NOI18N
        jlbIconUpdate.setText("jLabel4");

        jbtnUpdate.setBackground(new java.awt.Color(51, 153, 0));
        jbtnUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnUpdate.setText("Update");

        jbtnSearchToUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jbtnSearchToUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnSearchToUpdate.setText("Search");

        jlbNewName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbNewName.setForeground(new java.awt.Color(0, 0, 0));
        jlbNewName.setText("Name:");

        jlbLastName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbLastName.setForeground(new java.awt.Color(0, 0, 0));
        jlbLastName.setText("Lastname:");

        jlbNewIdCode.setBackground(new java.awt.Color(0, 0, 0));
        jlbNewIdCode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbNewIdCode.setForeground(new java.awt.Color(0, 0, 0));
        jlbNewIdCode.setText("Job ID:");

        jtxfNewLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfNewLastnameActionPerformed(evt);
            }
        });

        jbtnExit3.setBackground(new java.awt.Color(153, 0, 0));
        jbtnExit3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtnExit3.setText("Exit");

        javax.swing.GroupLayout jpnlSecond3Layout = new javax.swing.GroupLayout(jpnlSecond3);
        jpnlSecond3.setLayout(jpnlSecond3Layout);
        jpnlSecond3Layout.setHorizontalGroup(
            jpnlSecond3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecond3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit3)
                .addContainerGap())
        );
        jpnlSecond3Layout.setVerticalGroup(
            jpnlSecond3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSecond3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jbtnExit3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(113, 113, 113)
                                .addComponent(jlbIconUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnSearchToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxfSearchToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnUpdate)
                                .addGap(79, 79, 79))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbNewName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbLastName)
                                .addGap(117, 117, 117)
                                .addComponent(jlbNewIdCode, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxfNewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jtxfNewNewJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addComponent(jpnlSecond3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jlbIconUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfSearchToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnUpdate)
                    .addComponent(jbtnSearchToUpdate))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNewName)
                    .addComponent(jlbLastName)
                    .addComponent(jlbNewIdCode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfNewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfNewNewJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jpnlSecond3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpnJanitorCRUD.addTab("Update", jInternalFrame3);

        jInternalFrame4.setVisible(true);

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jtpnJanitorCRUD.addTab("List", jInternalFrame4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpnJanitorCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpnJanitorCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSearchToDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchToDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSearchToDeleteActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jtxfNewLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfNewLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfNewLastnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit1;
    private javax.swing.JButton jbtnExit2;
    private javax.swing.JButton jbtnExit3;
    private javax.swing.JButton jbtnSearchToDelete;
    private javax.swing.JButton jbtnSearchToUpdate;
    private javax.swing.JButton jbtnSignIn;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlbDeleteIcon;
    private javax.swing.JLabel jlbErrorDelete;
    private javax.swing.JLabel jlbIconAdd;
    private javax.swing.JLabel jlbIconUpdate;
    private javax.swing.JLabel jlbId;
    private javax.swing.JLabel jlbJobId;
    private javax.swing.JLabel jlbLastName;
    private javax.swing.JLabel jlbLastname;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbNewIdCode;
    private javax.swing.JLabel jlbNewName;
    private javax.swing.JLabel jlbSecondTittle;
    private javax.swing.JLabel jlbSuccessToDelete;
    private javax.swing.JPanel jpnlAddJanitor;
    private javax.swing.JPanel jpnlDelete;
    private javax.swing.JPanel jpnlSecodDelete;
    private javax.swing.JPanel jpnlSecond3;
    private javax.swing.JPanel jpnlSecondPanel;
    private javax.swing.JTabbedPane jtpnJanitorCRUD;
    private javax.swing.JTextArea jtxaAddInfo;
    private javax.swing.JTextField jtxfId;
    private javax.swing.JTextField jtxfJobId;
    private javax.swing.JTextField jtxfLastname;
    private javax.swing.JTextField jtxfName;
    private javax.swing.JTextField jtxfNewLastname;
    private javax.swing.JTextField jtxfNewName;
    private javax.swing.JTextField jtxfNewNewJobId;
    private javax.swing.JTextField jtxfSearchToDelete;
    private javax.swing.JTextField jtxfSearchToUpdate;
    // End of variables declaration//GEN-END:variables
}
